apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: cygnetops/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: cygnetops/assets
      context: assets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: cygnetops/scans
      context: scans
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
#    - image: cygnetops/tickets
#      context: tickets
#      docker:
#        dockerfile: Dockerfile
#      sync:
#        manual:
#          - src: 'src/**/*.ts'
#            dest: .
#    - image: cygnetops/orders
#      context: orders
#      docker:
#        dockerfile: Dockerfile
#      sync:
#        manual:
#          - src: 'src/**/*.ts'
#            dest: .
#    - image: cygnetops/auth
#      context: auth
#      docker:
#        dockerfile: Dockerfile
#      sync:
#        manual:
#          - src: 'src/**/*.ts'
#            dest: .
