apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
spec:
  ingressClassName: nginx
  rules:
    - host: assets.dev
      http:
        paths:
          - path: /api/assets
            pathType: Prefix
            backend:
              service:
                name: assets-srv
                port: 
                  number: 3000
          - path: /api/scans
            pathType: Prefix
            backend:
              service:
                name: scans-srv
                port: 
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port: 
                  number: 3000